"""센서 enum 정의.

원본 매핑 (swm → 신규):
- App/Category/eSensor.py::E_SENSOR_TYPE → E_SENSOR_TYPE (그대로)
- App/Category/eSensor.py::E_LIDAR      → E_LIDAR (그대로)
- App/Category/eSensor.py::E_CAMERA     → E_CAMERA (그대로)
- (swm에는 enum 클래스 없이 문자열만 사용하던 GNSS) → E_GNSS 추가
싱글톤 등록자(swm의 EC_SENSOR)는 common/singleton/sensor_registry.py로 분리.
"""

from python_library.define.enum import IENUM


class E_SENSOR_TYPE(IENUM):
    ALL = "ALL"
    GNSS = "GNSS"
    LIDAR = "LIDAR"
    CAMERA = "CAMERA"


class E_LIDAR(IENUM):
    AT128_ROOF_FRONT = "AT128_ROOF_FRONT"
    AT128_ROOF_RIGHT = "AT128_ROOF_RIGHT"
    AT128_ROOF_REAR = "AT128_ROOF_REAR"
    AT128_ROOF_LEFT = "AT128_ROOF_LEFT"
    RSBP_BUMP_FRONT = "RSBP_BUMP_FRONT"
    RSBP_BUMP_RIGHT = "RSBP_BUMP_RIGHT"
    RSBP_BUMP_REAR = "RSBP_BUMP_REAR"
    RSBP_BUMP_LEFT = "RSBP_BUMP_LEFT"


class E_CAMERA(IENUM):
    AM20_FRONT_CENTER_RIGHT_DOWN = "AM20_FRONT_CENTER_RIGHT_DOWN"
    AM20_FRONT_RIGHT_REAR = "AM20_FRONT_RIGHT_REAR"
    AM20_REAR_CENTER_RIGHT = "AM20_REAR_CENTER_RIGHT"
    AM20_FRONT_LEFT_REAR = "AM20_FRONT_LEFT_REAR"
    AM20_REAR_RIGHT_EDGE = "AM20_REAR_RIGHT_EDGE"
    AM20_LEFT_REAR_EDGE = "AM20_LEFT_REAR_EDGE"
    AM20_FRONT_CENTER_LEFT_UP = "AM20_FRONT_CENTER_LEFT_UP"
    AM20_FRONT_CENTER_RIGHT_UP = "AM20_FRONT_CENTER_RIGHT_UP"
    AM20_FRONT_RIGHT_FRONT = "AM20_FRONT_RIGHT_FRONT"
    AM20_FRONT_LEFT_FRONT = "AM20_FRONT_LEFT_FRONT"


class E_GNSS(IENUM):
    GNSS = "GNSS"
